name: node.js build & push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout sources
      uses: actions/checkout@v5
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v6

    - name: Setup Node.js 🔧
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'
        
    - name: CI ⚙
      run: pnpm install --frozen-lockfile
      
    - name: Build 🏗️
      run: pnpm run build

    - name: Deploy to GH Pages 🚀
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
